feat(schema): basic framework of schema
casbin-mesh/neo pull request #25
Opened 2022-06-24 08:08 UTC by noneback

2022-06-24 14:01 UTC, WenyXu commented on pkg/schema.go
> +	header := []byte(bs.namespace + separator + bs.name + separator)
double check it later

2022-06-24 14:08 UTC, WenyXu commented
1. Put the updating dependencies into an independent pull request
2. Remove the irrelevant codes
4. Don't touch other irrelevant codes

2022-06-24 14:09 UTC, noneback commented on pkg/schema.go
> +	name      string
You mean change `typ` to byte array or string type to byte array ?

2022-06-25 13:42 UTC, WenyXu commented on pkg/codec/codec.go
> +	decode([]byte) interface{}
unexported function

2022-06-25 13:48 UTC, WenyXu requested changes
1. Implement the unimplemented functions
2. Add the tests.

2022-06-25 13:48 UTC, WenyXu commented on pkg/codec/codec.go
> +	encodeKey() []byte
unexported function

2022-06-25 13:48 UTC, WenyXu commented on pkg/codec/codec.go
> +	encodeVal() []byte
unexported function

2022-06-25 13:48 UTC, WenyXu commented on pkg/schema/schema.go
> +	buf := make([]byte, 0) // TODO: optimize later
The exact size is known

2022-06-25 13:48 UTC, WenyXu commented on pkg/schema/schema.go
> +func (bs *BSchema) decode([]byte) {}
unimplemented

2022-06-25 13:48 UTC, WenyXu commented on pkg/schema/schema.go
> +	SchemaTypePolicy = 0
Can we use the null terminator here? It seems problematic.

2022-06-25 13:48 UTC, WenyXu commented on pkg/schema/field.go
> +	FieldTypeBinary = 1
let's follow the bson type definition. https://github.com/casbin-mesh/neo/blob/feat/btuple-weny/pkg/primitive/bsontype/bsontype.go

2022-07-03 09:32 UTC, WenyXu approved these changes

2022-07-03 09:34 UTC, merged